---
- name: install-docker | Ensure if docker has already installed
  stat:
    path: /usr/bin/docker
  register: docker_bin

- name: install-docker | Add Docker’s official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    validate_certs: no
  when: docker_bin.stat.exists == false

- name: install-docker |
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    update_cache: yes
  when: docker_bin.stat.exists == false

- name: install-docker | Install Docker
  apt:
    pkg: docker-ce
  when: docker_bin.stat.exists == false
